function P = pack_boiler_params()
% Snapshot current base-workspace constants into a struct for the utilities.
    f = {'Water_Mass_kg','Cp_Water','UA_Losses','P_Internal_W','P_Boost_W', ...
         'h_Boost','A_Boost','V_Supply','T_Ambient_C','T_Initial_C','T_Comfort_C', ...
         'T_dumb_target','T_target_logic','Rho_Water','T_Water_Inlet_C', ...
         'T_Max_Cutoff_C','Solar_Gain_Coeff','T_Sheath_Limit_C'};
    for i = 1:numel(f), P.(f{i}) = evalin('base', f{i}); end
end